[package]
name = "hvm64-num"
version.workspace = true
edition = "2021"

[lib]
path = "src/num.rs"

[dependencies]
hvm64-util = { path = "../util", default-features = false }

[features]
default = ["std"]
std = ["hvm64-util/std"]

[lints]
workspace = true
