[package]
name = "hvm-core"
version = "0.1.11"
edition = "2021"
description = "HVM-Core is a massively parallel Interaction Combinator evaluator."
license = "MIT"

[[bin]]
name = "hvmc"
path = "src/main.rs"

[lib]
name = "hvmc"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.5.1"
hvm-lang = { git = "https://github.com/HigherOrderCO/hvm-lang.git" }

[patch."https://github.com/HigherOrderCO/hvm-core.git"]
hvm-core = { path = "." }


[[bench]]
name = "hvm_cpu"
harness = false
