[package]
name = "hvm-core"
version = "0.2.11"
edition = "2021"
description = "HVM-Core is a massively parallel Interaction Combinator evaluator."
license = "MIT"

[[bin]]
name = "hvmc"
path = "src/main.rs"
bench = false

[lib]
name = "hvmc"
path = "src/lib.rs"
bench = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[features]
default = ["hvm_cli_options"]
hvm_cli_options = []

[dependencies]
fastrand = "2.0.1"
nohash-hasher = "0.2.0"
st3 = "0.4.1"

##--COMPILER-CUTOFF--##

[dev-dependencies]
criterion = "0.5.1"
hvm-lang = { git = "https://github.com/HigherOrderCO/hvm-lang.git" } # allows us to use the hvm-lang syntax for tests/benchmarks
insta = "1.34.0"

[patch."https://github.com/HigherOrderCO/hvm-core.git"]
hvm-core = { path = "." }

[[bench]]
name = "benches"
harness = false
