[package]
name = "hvm-core"
version = "0.2.19"
edition = "2021"
description = "HVM-Core is a massively parallel Interaction Combinator evaluator."
license = "MIT"

[[bin]]
name = "hvmc"
path = "src/main.rs"
bench = false

[lib]
name = "hvmc"
path = "src/lib.rs"
bench = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
debug = "full"

[dependencies]
nohash-hasher = { version = "0.2.0" }

##--COMPILER-CUTOFF--##

[features]
default = ["_full_cli"]
trace = []
_full_cli = []
_fuzz = []
_fuzz_no_free = ["_fuzz"]

[dev-dependencies]
criterion = "0.5.1"
hvm-lang = { git = "https://github.com/HigherOrderCO/hvm-lang.git", branch = "core-ptr-refactor/sc-362/basic-compatibility" } # allows us to use the hvm-lang syntax for tests/benchmarks
insta = "1.34.0"
serial_test = "3.0.0"

[patch."https://github.com/HigherOrderCO/hvm-core.git"]
hvm-core = { path = "." }

[[bench]]
name = "benches"
harness = false
