[package]
name = "hvm-core"
version = "0.2.24"
edition = "2021"
description = "HVM-Core is a massively parallel Interaction Combinator evaluator."
license = "MIT"

[[bin]]
name = "hvmc"
path = "src/main.rs"
bench = false

[lib]
name = "hvmc"
path = "src/lib.rs"
bench = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
debug = "full"

[dependencies]
arrayvec = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
nohash-hasher = { version = "0.2.0" }
ordered-float = "4.2.0"
stacker = "0.1.15"
thiserror = "1.0.58"

##--COMPILER-CUTOFF--##

[features]
default = ["_full_cli"]
trace = []
_full_cli = []
_fuzz = []
_fuzz_no_free = ["_fuzz"]

[dev-dependencies]
insta = { version = "1.34.0", features = ["glob"] }
serial_test = "3.0.0"
