[package]
name = "hvm-core"
version = "0.1.12"
edition = "2021"
description = "HVM-Core is a massively parallel Interaction Combinator evaluator."
license = "MIT"

[[bin]]
name = "hvmc"
path = "src/main.rs"
bench = false

[lib]
name = "hvmc"
path = "src/lib.rs"
bench = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[features]
default = ["hvm_cli_options"]
hvm_cli_options = ["dep:proc-macro2", "dep:quote", "dep:rust-format"]

[dependencies]
proc-macro2 = {optional = true, version = "1.0.69"}
quote = {optional = true, version = "1.0.33"}
rust-format = {optional = true, version = "0.3.4"}
cranelift = "0.102.1"
cranelift-jit = "0.102.1"
cranelift-module = "0.102.1"
cranelift-native = "0.102.1"

##--COMPILER-CUTOFF--##

# Benchmark dependencies

[dev-dependencies]
criterion = "0.5.1"
hvm-lang = { git = "https://github.com/HigherOrderCO/hvm-lang.git" } # allows us to use the hvm-lang syntax for tests/benchmarks
insta = "1.34.0"

[patch."https://github.com/HigherOrderCO/hvm-core.git"]
hvm-core = { path = "." }

[[bench]]
name = "benches"
harness = false
