[package]
name = "hvm64-runtime"
version = "0.3.0"
edition = "2021"

[lib]
path = "src/runtime.rs"

[dependencies]
hvm64-util = { path = "../util" }

[features]
default = ["std"]
std = []
trace = ["std"]

[lints]
workspace = true
