[package]
name = "hvm64-util"
version.workspace = true
edition = "2021"

[dependencies]
stacker = { version = "0.1.15", optional = true }

[features]
default = ["std"]
std = ["dep:stacker"]

[lints]
workspace = true
