name: Bench

on:
  pull_request:

concurrency:
  group: bench-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-check-${{ hashFiles('**/Cargo.lock') }}
      - name: compare perf
        run: |
          git clone https://github.com/higherorderco/hvm-compare-perf
          cd hvm-compare-perf
          NO_COLOR=1 cargo run bench -r main -r ${{ github.sha }} -f programs/c2.hvmc > ../table
      - name: write comment
        run: |
          echo 'Perf run for [`'`git rev-parse --short ${{ github.sha }}`'`](https://github.com/higherorderco/hvm-core/commit/${{ github.sha }}):' >> comment
          echo '```' >> comment
          cat table >> comment
          echo '```' >> comment
      - name: post comment
        run: gh pr comment ${{ github.event.number }} -F comment
        env:
          GH_TOKEN: ${{ github.token }}
